# Generated by Django 4.1.7 on 2023-03-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_rename_user_id_watchlist_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='User',
            new_name='user',
        ),
    ]
