# Generated by Django 4.1.7 on 2023-03-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('time_publish', models.DateTimeField()),
                ('genre', models.CharField(max_length=150)),
                ('poster_url', models.CharField(max_length=255)),
                ('trailer_url', models.CharField(max_length=255)),
            ],
        ),
    ]
